{{- if and .Values.oauthProxy.enabled | default false .Values.oauthProxy.config.createSecret | default false }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.oauthProxy.config.secretKey | default "secret" }}: "{{ .Values.oauthProxy.config.oauthSecret | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.oauthProxy.config.secretName | default (printf "%s-oauth" (include "kafka-connect-ui.fullname" .)) }}
  labels:
    {{- include "kafka-connect-ui.labels" . | nindent 4 }}
{{- end }}

