apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}
  labels:
    {{- include "witcom-id-generator.labels" . | nindent 4 }}
data:
  generatorconfig.json: {{ .Values.generator.config | toJson }}
