{{- if and .Values.rbac.create .Values.rbac.rules }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "witcom-id-generator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "witcom-id-generator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
