apiVersion: v1
kind: Service
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}-webapp
  labels:
    {{- include "witcom-id-generator.webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "witcom-id-generator.webapp.selectorLabels" . | nindent 4 }}
