apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}-webapp
  labels:
    {{- include "witcom-id-generator.webapp.labels" . | nindent 4 }}
data:
  appconfig.json: {{ .Values.webapp.config | toJson }}
