apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witcom-id-generator.fullname" . }}-webapp
  labels:
    {{- include "witcom-id-generator.webapp.labels" . | nindent 4 }}
spec:
{{- if not .Values.webapp.autoscaling.enabled }}
  replicas: {{ .Values.webapp.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "witcom-id-generator.webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webapp-configmap.yaml") . | sha256sum }}     
      {{- with .Values.webapp.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "witcom-id-generator.webapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.webapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "witcom-id-generator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webapp.podSecurityContext | nindent 8 }}
      containers:
        - name: generator-webapp
          securityContext:
            {{- toYaml .Values.webapp.securityContext | nindent 12 }}
          image: "{{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}"
          imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
          env:
            {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.extraEnvFrom }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.webapp.service.port }}
              protocol: TCP
          {{- with .Values.webapp.livenessProbe }}
          livenessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.webapp.readinessProbe }}
          readinessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.webapp.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/opt/app-root/src/assets/configdata"
              readOnly: true
      {{- with .Values.webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webapp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "witcom-id-generator.fullname" . }}-webapp
