# Default values for vaultwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config:
  domain: ""
  signupsAllowed: "true"
  invitationsAllowed: "true"
  showPasswordHint: "false"
  dataFolder: data
  database:
    url: data/db.sqlite3
    connectionInit: ""
    maxConnections: 10
  smtp:
    host: ""
    from: ""
    fromName: ""
    # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 is outdated and used with Implicit TLS.
    port: 587
    #"starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
    security: starttls
    username:
    password:
  adminToken:
    enabled: true
    createSecret: true   
    #Defaults to <release-name>
    secretName: ""
    secretKey: admin-token
    #if set and createSecret is set create the secret
    token: ""

backup:
  enabled: false
  ## @param backup.retention Backup-Retention in days. Defaults to 30. Beware - this is set on bucket level, so please coordinate the values
  retention: "30"
  ## @param backup.schedule Backup-Schedule as cron-job. Defaults to every 4 hours.
  schedule: "0 */4 * * *"
  ## @param backup.cronJobLabels Labels for cron-jobs and job-instances
  cronJobLabels: {}
  ## @param backup.podLabels Labels for backup-pods, can be useful for Networkpolicies
  podLabels: {}
  resources: {}
  image:
    ## @param backup.image.repository - backup-image. See https://github.com/witcom-gmbh/vaultwarden-s3-backup
    repository: my-registry/someorg/vaultwarden-s3-backup
    pullPolicy: IfNotPresent
    tag: "0.1.2"      
  s3:
    ## @param backup.s3.endpoint S3-Endpoint - Required
    endpoint: 
    ## @param backup.s3.bucket S3-Bucket - Required
    bucket: 
    ## @param backup.s3.prefix Folder in given S3-Bucket
    #if not present, will be same as vaultwarden.fullname
    prefix: "" 
    ## @param backup.s3.existingSecret Take S3 Secret-Access-Key and S3 Secret-Access-Key from an existing secret
    ## with keys S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY
    #existingSecret: "my-secret" 
    ## @param backup.s3.accessKeyId S3 Access-Key-ID
    accessKeyId: 
    ## @param backup.s3.secretAccessKey S3 Secret-Access-Key
    secretAccessKey: 



extraEnv: ""

#extraEnv: |
#  - name: YUBICO_CLIENT_ID
#    value: ++++++

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Persist data to a persitent volume
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 800Mi
  #storageClass:
  #existingClaim: "bitwarden-pvc"