dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 7.5.2
    alias: mariadbzimuaa
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 7.5.2
    alias: mariadbfrontend

