apiVersion: v1
kind: Secret
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.frontend" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.frontend" . }}
type: Opaque
data:
  ZIMFRONTEND_OAUTH_SECRET: {{ default "" .Values.frontend.identity.oauthSecret | b64enc | quote  }}
  ZIMFRONTEND_OAUTH_CLIENT: {{ default "" .Values.frontend.identity.oauthClient | b64enc | quote  }}
