apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.frontend" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.frontend" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "witcom-zim.name" . }}-{{ include "witcom-zim-component.frontend" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ include "witcom-zim-component.frontend" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "witcom-zim.name" . }}-{{ include "witcom-zim-component.frontend" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ include "witcom-zim-component.frontend" . }}
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.frontend" . }}
          env:
          - name: ZIMFRONTEND_DB_USER
            value: {{ .Values.mariadbfrontend.db.user }}
          - name: ZIMFRONTEND_DB_PASSWORD
            value: {{ .Values.mariadbfrontend.db.password }}
          - name: ZIMFRONTEND_DB_HOST
            value: {{ include "frontend.mariadb.fullname" . }}
          - name: ZIMFRONTEND_DB_NAME
            value: {{ .Values.mariadbfrontend.db.name }}
          - name: LABELSVC_SVC_NAME
            value: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.labelsvc" . }}
          - name: LABELSVC_SVC_PORT
            value: {{ .Values.labelsvc.service.port | quote}}
          - name: ZIMUAA_SVC_NAME 
            value: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.uaa" . }}
          - name: ZIMUAA_SVC_PORT
            value: {{ .Values.zimuaa.service.port | quote}}
          - name: RMDBSVC_SVC_NAME 
            value: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.rmdbsvc" . }}
          - name: RMDBSVC_SVC_PORT
            value: {{ .Values.rmdbsvc.service.port | quote}}
          name: {{ .Chart.Name }}-{{ include "witcom-zim-component.frontend" . }}
          image: "{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: {{ include "witcom-zim-component.frontend" . }}-api
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health
              port: {{ .Values.frontend.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3  
          readinessProbe:
            httpGet:
              path: /management/health
              port: {{ .Values.frontend.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
