apiVersion: v1
kind: Service
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.rmdbsvc" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.rmdbsvc" . }}
spec:
  type: {{ .Values.rmdbsvc.service.type }}
  ports:
    - port: {{ .Values.rmdbsvc.service.port }}
      targetPort: {{ .Values.rmdbsvc.service.port }}
      protocol: TCP
      name: {{ include "witcom-zim-component.rmdbsvc" . }}-api
  selector:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}-{{ include "witcom-zim-component.rmdbsvc" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.rmdbsvc" . }}     
