apiVersion: v1
kind: Secret
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.rmdbsvc" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.rmdbsvc" . }}
type: Opaque
data:
  CMD_JDBC_PASSWORD: {{ default "" .Values.rmdbsvc.command.jdbc.password | b64enc | quote }}
  CMD_PASSWORD: {{ default "" .Values.rmdbsvc.command.api.password | b64enc | quote  }}
  ZIM_RMDBSVC_OAUTH_SECRET: {{ default "" .Values.rmdbsvc.identity.oauthSecret | b64enc | quote  }}
  ZIM_RMDBSVC_OAUTH_CLIENT: {{ default "" .Values.rmdbsvc.identity.oauthClient | b64enc | quote  }}
