apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.rmdbsvc" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.rmdbsvc" . }}
data:
  CMD_JDBC_URL: {{ .Values.rmdbsvc.command.jdbc.url }}
  CMD_JDBC_USER: {{ .Values.rmdbsvc.command.jdbc.user }}
  CMD_USER: {{ .Values.rmdbsvc.command.api.user }}
  CMD_BASE_URL: {{ .Values.rmdbsvc.command.api.baseUrl }}


