{{- if .Values.zimuaa.ingress.private.enabled -}}
{{- $fullName := include "witcom-zim.fullname" . -}}
{{- $svcPort := .Values.zimuaa.service.port -}}
{{- if and .Values.zimuaa.ingress.private.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.zimuaa.ingress.private.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.zimuaa.ingress.private.annotations "kubernetes.io/ingress.class" .Values.zimuaa.ingress.private.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ include "witcom-zim-component.uaa" . }}-private
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.uaa" . }}    
  {{- with .Values.zimuaa.ingress.private.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.zimuaa.ingress.private.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.zimuaa.ingress.private.className }}
  {{- end }}
  {{- if .Values.zimuaa.ingress.private.tls }}
  tls:
    {{- range .Values.zimuaa.ingress.private.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.zimuaa.ingress.private.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-{{ include "witcom-zim-component.uaa" . }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-{{ include "witcom-zim-component.uaa" . }}
              servicePort: {{ include "witcom-zim-component.uaa" . }}-api
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
