apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witcom-zim.fullname" . }}-{{ include "witcom-zim-component.uaa" . }}
  labels:
    app.kubernetes.io/name: {{ include "witcom-zim.name" . }}
    helm.sh/chart: {{ include "witcom-zim.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ include "witcom-zim-component.uaa" . }}
spec:
  replicas: {{ .Values.zimuaa.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "witcom-zim.name" . }}-{{ include "witcom-zim-component.uaa" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ include "witcom-zim-component.uaa" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "witcom-zim.name" . }}-{{ include "witcom-zim-component.uaa" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: {{ include "witcom-zim-component.uaa" . }}
    spec:
      containers:
        - env:
            - name: ZIM_UAA_DB_USER
              value: {{ .Values.mariadbzimuaa.db.user }}
            - name: ZIM_UAA_DB_PASS
              value: {{ .Values.mariadbzimuaa.db.password }}
            - name: ZIM_UAA_DB_HOST
              value: {{ include "zimuaa.mariadb.fullname" . }}
            - name: ZIM_UAA_DB_NAME
              value: {{ .Values.mariadbzimuaa.db.name }}
            - name: ZIM_UAA_WSO2_CLIENT_ID
              value: {{ .Values.zimuaa.wso2.client }}
            - name: ZIM_UAA_WSO2_CLIENT_SECRET
              value: {{ .Values.zimuaa.wso2.secret }}
            - name: IDENTITY_BASE_URL
              value: {{ .Values.zimuaa.wso2.url }}
            - name: ZIM_UAA_PORT         
              value: "{{ .Values.zimuaa.service.port }}"
            - name: ZIM_UAA_OAUTH_CLIENT
              value: {{ .Values.zimuaa.identity.oauthClient }}
            - name: ZIM_UAA_OAUTH_CLIENT_SECRET
              value: {{ .Values.zimuaa.identity.oauthSecret }}
            - name: ZIM_UAA_BASEURL
              value: {{ .Values.frontend.baseUrl }}
          name: {{ .Chart.Name }}-{{ include "witcom-zim-component.uaa" . }}
          image: "{{ .Values.zimuaa.image.name }}:{{ .Values.zimuaa.image.tag }}"
          imagePullPolicy: {{ .Values.zimuaa.image.pullPolicy }}
          ports:
            - name: {{ include "witcom-zim-component.uaa" . }}-api
              containerPort: {{ .Values.zimuaa.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health
              port: {{ .Values.zimuaa.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3  
          readinessProbe:
            httpGet:
              path: /management/health
              port: {{ .Values.zimuaa.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.zimuaa.resources | nindent 12 }}
      {{- with .Values.zimuaa.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.zimuaa.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.zimuaa.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
