{{- if .Values.secureAccess.createSecret }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.secureAccess.clientSecretKey | default "secret" }}: "{{ .Values.secureAccess.secret | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.secureAccess.clientSecretName | default (printf "%s-secure-access" (include "apicurio-registry-sql.fullname" .)) }}
  labels:
    {{- include "apicurio-registry-sql.labels" . | nindent 4 }}
{{- end }}
