{{- if not .Values.secureAccess.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apicurio-registry-sql.fullname" . }}
  labels:
    {{- include "apicurio-registry-sql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apicurio-registry-sql.selectorLabels" . | nindent 4 }}
{{- end }}
