{{- $configMap := toYaml .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmware-exporter.fullname" . }}
  labels:
    {{- include "vmware-exporter.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ tpl $configMap . | indent 4 }}
