apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdnsadmin.fullname" . }}
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
data:
  SQLALCHEMY_DATABASE_URI: {{ tpl "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{.Values.postgres.port | toString }}/{{ .Values.postgres.database }}" . | b64enc | quote }}
