{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "powerdnsadmin.serviceAccountName" . }}
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
{{- end -}}
