apiVersion: v1
data:
  app-config.json: |+
    {{ toJson .Values.settings }}

kind: ConfigMap
metadata:
  name: {{ include "itsm-portal-webapp.fullname" . }}
  labels:
    {{- include "itsm-portal-webapp.labels" . | nindent 4 }}

