{{- if and .Values.config.adminToken.createSecret (and .Values.config.adminToken.enabled .Values.config.adminToken.token )  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
{{ include "vaultwarden.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.config.adminToken.secretKey | default "admin-token" }}: {{ tpl "{{ .Values.config.adminToken.token }}" . | b64enc | quote }}
{{- end }}