{{- if eq (include "dbbackup.createSecret" .) "true" }}
apiVersion: v1
type: Opaque
data:
  S3_ACCESS_KEY_ID: "{{ .Values.backup.s3.accessKeyId | b64enc }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.backup.s3.secretAccessKey | b64enc }}"
kind: Secret
metadata:
  name: {{ include "dbbackup.secretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
{{- end }}