{{- if .Values.search.auth.createSecret }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.search.auth.passwordKey | default "password" }}: "{{ .Values.search.auth.password | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.search.auth.secretName | default (printf "%s-search" (include "itsm-portal-api.fullname" .)) }}
  labels:
    {{- include "itsm-portal-api.labels" . | nindent 4 }}
{{- end }}

