{{- if .Values.oauth.createClientSecret }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.oauth.clientSecretKey | default "secret" }}: "{{ .Values.oauth.clientSecret | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.oauth.clientSecretName | default (printf "%s-oauth" (include "itsm-portal-api.fullname" .)) }}
  labels:
    {{- include "itsm-portal-api.labels" . | nindent 4 }}
{{- end }}

