{{- if .Values.db.createSecret }}
apiVersion: v1
type: Opaque
data:
  {{ .Values.db.secretKey | default "secret" }}: "{{ .Values.oauth.secret | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.db.secretName | default (printf "%s-db" (include "itsm-portal-api.fullname" .)) }}
  labels:
    {{- include "itsm-portal-api.labels" . | nindent 4 }}
{{- end }}

