apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extranet-docs-docservice.fullname" . }}
  labels:
    {{- include "extranet-docs-docservice.labels" . | nindent 4 }}
data:
  EXTRANETDOCS_RESTCLIENTS_NOCAPIURL: {{ .Values.config.nocApiBasePath }}
  EXTRANETDOCS_OAUTH_ISSUER_URI: {{ .Values.config.keycloak.providerIssuerUri }}
  EXTRANETDOCS_OAUTH_CLIENTID: {{ .Values.config.keycloak.clientId }}
  EXTRANETDOCS_S3_ENDPOINT: {{ .Values.config.s3.endpoint }}
  EXTRANETDOCS_S3_BUCKET: {{ .Values.config.s3.bucket }}
  EXTRANETDOCS_DATABASE_HOST: {{ .Values.config.db.host | default "localhost" }}
  EXTRANETDOCS_DATABASE_PORT: "{{ .Values.config.db.port | default "27017" }}"
  EXTRANETDOCS_DATABASE_NAME: {{ .Values.config.db.name | default "docs" }}
  SPRING_DATA_MONGODB_USERNAME: {{ .Values.config.db.user | default "user" }}

