apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extranet-docs-docservice.fullname" . }}
  labels:
    {{- include "extranet-docs-docservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "extranet-docs-docservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "extranet-docs-docservice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "extranet-docs-docservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "extranet-docs-docservice.fullname" . }}
          env:
            - name: EXTRANETDOCS_OAUTH_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.keycloak.clientSecretName | default (include "extranet-docs-docservice.defaultSecret" .) }}
                  key: {{ .Values.config.keycloak.clientSecretKey | default "keycloak-secret" }}
            - name: EXTRANETDOCS_S3_ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.s3.s3SecretName | default (include "extranet-docs-docservice.defaultSecret" .) }}
                  key: {{ .Values.config.s3.accessKeyIdSecretKey | default "access-key-id" }}
            - name: EXTRANETDOCS_S3_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.s3.s3SecretName | default (include "extranet-docs-docservice.defaultSecret" .) }}
                  key: {{ .Values.config.s3.accessKeySecretKey | default "access-key" }}
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.db.passwordSecretName | default (include "extranet-docs-docservice.defaultSecret" .) }}
                  key: {{ .Values.config.db.passwordSecretKey | default "db-secret" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/liveness
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
