{{- if .Values.config.createSecret }}
apiVersion: v1
type: Opaque
data:
  {{ if .Values.config.db.password }}{{ .Values.config.db.passwordSecretKey | default "db-secret" }}: "{{ .Values.config.db.password | b64enc }}"{{ end }}
  {{ if .Values.config.keycloak.clientSecret }}{{ .Values.config.keycloak.clientSecretKey | default "keycloak-secret" }}: "{{ .Values.config.keycloak.clientSecret | b64enc  }}"{{ end }}
  {{ .Values.config.s3.accessKeyIdSecretKey | default "access-key-id" }}: "{{ .Values.config.s3.accessKeyId | b64enc }}"
  {{ .Values.config.s3.accessKeySecretKey | default "access-key" }}: "{{ .Values.config.s3.accessKey | b64enc }}"
kind: Secret
metadata:
  name: {{ .Values.config.defaultSecretName | default (include "extranet-docs-docservice.defaultSecret" .) }}
  labels:
    {{- include "extranet-docs-docservice.labels" . | nindent 4 }}
{{- end }}

