{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "extranet-docs-docservice.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
        {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "extranet-docs-docservice.fullname" . }}
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    port: http
    path: /prometheus
  selector:
    matchLabels:
      {{- include "extranet-docs-docservice.selectorLabels" . | nindent 6 }}
{{- end }}
