# Default values for witcom-id-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keycloak:
    serverUrl: 
    realm: 

generator:
  externalConfig:
    enabled: false
    #name of the configmap
    configmap: "" 

  keycloak:
    clientId: id-generator-service
    secretName: id-generator-keycloak
    secretKey: client-secret

  replicaCount: 1
  image:
    repository: witcom/id-generator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.2.4"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  #extraInitContainers: ""

  #extraContainers: ""

  # Additional environment variables for generator
  extraEnv: ""  

  # Additional environment variables for generator mapped from Secret or ConfigMap
  extraEnvFrom: ""  

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000


  livenessProbe: |
    httpGet:
      path: /-/live
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 5

  readinessProbe: |
    httpGet:
      path: /-/ready
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 1

  service:
    type: ClusterIP
    port: 3000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  autoscaling:
  # If `true`, a autoscaling/v2beta2 HorizontalPodAutoscaler resource is created (requires Kubernetes 1.18 or above)
  # Autoscaling seems to be most reliable when using KUBE_PING service discovery (see README for details)
  # This disables the `replicas` field in the StatefulSet
    enabled: false

redis:
  enabled: true
  cluster:
    enabled: false

webapp:

  apiUrl: ""
  keycloak:
    clientId: id-generator-webapp

  replicaCount: 1
  image:
    repository: witcom/id-generator-webapp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.0.8"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080


  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    #hosts:
    #  - host: chart-example.local
    #    paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  autoscaling:
  # If `true`, a autoscaling/v2beta2 HorizontalPodAutoscaler resource is created (requires Kubernetes 1.18 or above)
  # Autoscaling seems to be most reliable when using KUBE_PING service discovery (see README for details)
  # This disables the `replicas` field in the StatefulSet
    enabled: false


configmapReload:
  generator:
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.4.0
      pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  create: false
  rules: []
  # RBAC rules for KUBE_PING
  #  - apiGroups:
  #      - ""
  #    resources:
  #      - pods
  #    verbs:
  #      - get
  #      - list
