# Default values for witcom-id-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keycloak:
    serverUrl: 
    realm: 
    resourceId: 
    secretName: 
    secretKey: client-secret   

generator:
  config: |
    {
    "sequenceDefaults" : {
        "initialCursor": 1,
        "padding": "0",
        "maxValue": 99999999
    },
    "serviceTemplate" : [{
        "name":"Direkter Ciena LLDP-Link",
        "description":"Link zwischen direkt benachbarten Ciena Devices",
        "template":{
            "serviceOwner":"ABC",
            "serviceType":"LINK",
            "md":"A"
        },
        "type":"IS"
    },
    {
        "name":"Ciena MPLS-Tunnel",
        "description":"LSP zwischen Ciena-MPLS-Devices",
        "template":{
            "serviceOwner":"ABC",
            "serviceType":"PATH",
            "md":"A"
        },
        "type":"IS"
    }
    ],
    "sequenceDefinition" : [{
        "key": "LINK"

    },
    {
        "key": "NNI"

    },
    {
        "key": "PATH"

    },
    {
        "key": "CIRCUIT"

    },
    {
        "key": "IS"

    },
    {
        "key": "SERVICE"

    },
    {
        "key": "LL"

    }
    ],

    "managementDomain":[
    {
        "name":"blueplanet MCP",
        "id" : "A"
    },
    {
        "name":"Mixed",
        "id" : "Z"
    },
    {
        "name":"Unspecified",
        "id" : "Y"
    }

    ],
    "serviceOwner":[
    {
        "name" : "ABC Company",
        "id": "ABC"
    },
        {
        "name" : "WiTCOM",
        "id": "WIT"
    }
    ],
    "serviceType": [
    {
        "name": "Leased-Line",
        "id": "LL",
        "sequenceKey": "LL",
        "type": "IS-LL",
        "prefixTemplate": "##OWNER##-0Y##SEQ##"
    },
    {
        "name": "Telco Link",
        "id": "LINK",
        "sequenceKey": "LINK",
        "type": "IS-TELCO",
        "prefixTemplate": "##OWNER##-1##MD####SEQ##"
    },
    {
        "name": "Telco NNI",
        "id": "NNI",
        "sequenceKey": "NNI",
        "type": "IS-TELCO",
        "prefixTemplate": "##OWNER##-2Z##SEQ##"
    },
    {
        "name": "Telco Path",
        "id": "PATH",
        "sequenceKey": "PATH",
        "type": "IS-TELCO",
        "prefixTemplate": "##OWNER##-4##MD####SEQ##"
    },
    {
        "name": "Telco Circuit",
        "id": "CIRCUIT",
        "sequenceKey": "CIRCUIT",
        "type": "IS-TELCO",
        "prefixTemplate": "##OWNER##-6##MD####SEQ##"
    },
    {
        "name": "Infrastruktur-Service",
        "id": "IS",
        "sequenceKey": "IS",
        "type": "IS-SERVICE",
        "prefixTemplate": "##OWNER##-7Z##SEQ##"
    },
    {
        "name": "TEST-Service",
        "id": "TEST",
        "sequenceKey": "IS",
        "type": "IS-SERVICE",
        "prefixTemplate": "##OWNER##-99Z##SEQ##"
    },

    {
        "name": "Endkunden-Service",
        "id": "SERVICE",
        "sequenceKey": "SERVICE",
        "type": "CF-SERVICE",
        "prefixTemplate": "S-##SEQ##"
    }
    ]
    }

  replicaCount: 1
  image:
    repository: pub-registry.dev.witcom.services/witcom/id-generator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.2.0"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  extraInitContainers: ""

  extraContainers: ""

  # Additional environment variables for generator
  extraEnv: ""  

  # Additional environment variables for generator mapped from Secret or ConfigMap
  extraEnvFrom: ""  

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000


  livenessProbe: |
    httpGet:
      path: /-/health
      port: http
    initialDelaySeconds: 300
    timeoutSeconds: 5

  readinessProbe: |
    httpGet:
      path: /-/health
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 1

  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: false
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    #hosts:
    #  - host: chart-example.local
    #    paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  autoscaling:
  # If `true`, a autoscaling/v2beta2 HorizontalPodAutoscaler resource is created (requires Kubernetes 1.18 or above)
  # Autoscaling seems to be most reliable when using KUBE_PING service discovery (see README for details)
  # This disables the `replicas` field in the StatefulSet
    enabled: false

redis:
  enabled: true
  cluster:
    enabled: false

webapp:
  config: |
    {"APP_KEYCLOAK_URL: "","APP_KEYCLOAK_REALM": "witcom","APP_KEYCLOAK_RESOURCE_ID","id-generator","APP_API_URL":"https://api.witcom.services/id-generator"}

  replicaCount: 1
  image:
    repository: pub-registry.dev.witcom.services/witcom/id-generator-webapp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000

  service:
    type: ClusterIP
    port: 8080

  ingress:
    #enabled: false
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx-private
    #  kubernetes.io/tls-acme: "true"
    hosts:
      - host: id-generator.witcom.services
        paths:
          - /
    tls: 
      - secretName: tls-wildcard-witcom-services
        hosts:
          - id-generator.witcom.services

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  autoscaling:
  # If `true`, a autoscaling/v2beta2 HorizontalPodAutoscaler resource is created (requires Kubernetes 1.18 or above)
  # Autoscaling seems to be most reliable when using KUBE_PING service discovery (see README for details)
  # This disables the `replicas` field in the StatefulSet
    enabled: false


configmapReload:
  generator:
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.4.0
      pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  create: false
  rules: []
  # RBAC rules for KUBE_PING
  #  - apiGroups:
  #      - ""
  #    resources:
  #      - pods
  #    verbs:
  #      - get
  #      - list
